services:
  postgres:
    image: postgres:17
    container_name: setup_datawarehouse
    environment:
      POSTGRES_DB: SETUP
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "4102"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_setup
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@setup.com
      PGADMIN_DEFAULT_PASSWORD: "4102"
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata: